src/Entity/Job.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\JobRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JobRepository::class)
 */
class Job
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profession;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contract;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $salary;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $updated_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url_img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getContract(): ?string
    {
        return $this->contract;
    }

    public function setContract(string $contract): self
    {
        $this->contract = $contract;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->company);
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getUpdatedTime(): ?string
    {
        return $this->updated_time;
    }

    public function setUpdatedTime(string $updated_time): self
    {
        $this->updated_time = $updated_time;

        return $this;
    }

    public function getCreatedAt(): ?string
    {
        return $this->created_at;
    }

    public function setCreatedAt(string $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUrlImg(): ?string
    {
        return $this->url_img;
    }

    public function setUrlImg(string $url_img): self
    {
        $this->url_img = $url_img;

        return $this;
    }
}

src/Controller/AdminJobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Form\JobType;
use App\Repository\JobRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class AdminJobController extends AbstractController
{
    /**
     * @Route("/", name="app_admin_job_index", methods={"GET"})
     */
    public function index(JobRepository $jobRepository): Response
    {
        return $this->render('admin_job/index.html.twig', [
            'jobs' => $jobRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_admin_job_new", methods={"GET", "POST"})
     */
    public function new(Request $request, JobRepository $jobRepository): Response
    {
        $job = new Job();
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $jobRepository->add($job, true);

            return $this->redirectToRoute('app_admin_job_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_job/new.html.twig', [
            'job' => $job,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_job_show", methods={"GET"})
     */
    public function show(Job $job): Response
    {
        return $this->render('admin_job/show.html.twig', [
            'job' => $job,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_admin_job_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Job $job, JobRepository $jobRepository): Response
    {
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $jobRepository->add($job, true);

            return $this->redirectToRoute('app_admin_job_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_job/edit.html.twig', [
            'job' => $job,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_job_delete", methods={"POST"})
     */
    public function delete(Request $request, Job $job, JobRepository $jobRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$job->getId(), $request->request->get('_token'))) {
            $jobRepository->remove($job, true);
        }

        return $this->redirectToRoute('app_admin_job_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_job/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_job_delete', {'id': job.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cet offre d'emploie ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/admin_job/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-danger">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/admin_job/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Job{% endblock %}

{% block body %}
<div class="container w-75">
    <h1>Modifier l'annoncen°{{ job.id }}</h1>
    <div class="container text-center">
        {{ include('admin_job/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        <a class="text-danger text-decoration-none" href="{{ path('app_admin_job_index') }}">Retour à la liste</a>
        {{ include('admin_job/_delete_form.html.twig') }}
    </div>
</div>
    
{% endblock %}

templates/admin_job/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Job index{% endblock %}

{% block body %}
    <h1 class="text-danger">Gérer les offres d'emploies</h1>
    <div class="container text-center">
        <a class="text-danger text-decoration-none border border-danger rounded rounded-pill p-2" href="{{ path('app_admin_job_new') }}">Créer une nouvelle offre d'emploie</a>
    </div>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th class="text-light">Id</th>
                <th class="text-light">Métier</th>
                <th class="text-light">Contrat</th>
                <th class="text-light">Adresse</th>
                <th class="text-light">Entreprise</th>
                <th class="text-light">Salaires</th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
        {% for job in jobs %}
            <tr>
                <td class="text-light">{{ job.id }}</td>
                <td class="text-light">{{ job.profession }}</td>
                <td class="text-light">{{ job.contract }}</td>
                <td class="text-light">{{ job.city }} ({{ job.zipCode }}), {{ job.country }}</td>
                <td class="text-light">{{ job.company }}</td>
                <td class="text-light">{{ job.salary }} €</td>
                <td>
                    <a class="text-danger" href="{{ path('app_admin_job_show', {'id': job.id}) }}"><i class="bi bi-eye"></i></a>
                    <a class="text-danger" href="{{ path('app_admin_job_edit', {'id': job.id}) }}"><i class="bi bi-pencil-square"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucune offre d'emploie pour l'instant ..</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="container text-center">
        <a class="text-danger text-decoration-none border border-danger rounded rounded-pill p-2" href="{{ path('app_admin_job_new') }}">Créer une nouvelle offre d'emploie</a>
    </div>
{% endblock %}

templates/admin_job/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Job{% endblock %}

{% block body %}
<div class="container w-50">
    <h1 class="text-danger">Nouvelle offre d'emploie</h1>
    {{ include('admin_job/_form.html.twig') }}
    <a class="text-danger text-decoration-none" href="{{ path('app_admin_job_index') }}">Retour à la liste</a>
</div>

{% endblock %}

templates/admin_job/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Job{% endblock %}

{% block body %}
<div class="container w-75">
   <h1 class="text-danger">Annonce n°{{ job.id }}</h1>

    <table class="table table-dark table-striped">
        <tbody>
            <tr>
                <th>Titre de l'annonce</th>
                <td>{{ job.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ job.description }}</td>
            </tr>
            <tr>
                <th>Métier</th>
                <td>{{ job.profession }}</td>
            </tr>
            <tr>
                <th>Contrat</th>
                <td>{{ job.contract }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ job.country }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ job.city }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ job.zipCode }}</td>
            </tr>
            <tr>
                <th>Entreprise</th>
                <td>{{ job.company }}</td>
            </tr>
            <tr>
                <th>Salaire</th>
                <td>{{ job.salary }}</td>
            </tr>
        </tbody>
    </table>
    <div class="container text-center">
         <a class="text-danger p-2" href="{{ path('app_admin_job_index') }}">Retour à la liste</a>
        <a class="text-danger p-2" href="{{ path('app_admin_job_edit', {'id': job.id}) }}">Modifier l'annonce</a>
    </div>
        {{ include('admin_job/_delete_form.html.twig') }}
</div>
{% endblock %}